[package]

name = "nginx-rust"
version = "0.0.1"

[dependencies.term]
git = "https://github.com/rust-lang/term.git"

[dependencies.bitflags]
git = "https://github.com/rust-lang/bitflags.git"

[lib]
name = "nrust"
crate-type = ["dylib"]

[[bin]]
name = "nginx-make"
